services:
  - type: web
    name: cinematch-ai
    env: python
    rootDir: "Major Project"
    buildCommand: pip install -r requirements.txt
    startCommand: python src/app.py
    envVars:
      - key: PORT
        value: 5000
